### ISSUE TITLE
PHP Error after updating from 3.8.1-ol-7-r20 to 3.11.0-ol-7-r13

### ISSUE THREAD

**Issue by pixlol** [bitnami/bitnami-docker-matomo#37]
**Description**
I run into an PHP Error when updating from 3.8.1 to 3.11.0. 

**Steps to reproduce the issue:**
I am running the docker images in a swarm.
To update the service I change in my compose file from:
`image: bitnami/matomo:3.8.1-ol-7-r20`
to:
`image: bitnami/matomo:3.11.0-ol-7-r20`

**Describe the results you received:**
After updating the service with the new image in the logs of the service the following errors come up:
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Piwik\\Tracker\\GoalManager::detectGoalsMatchingUrl(), 2 passed in /bitnami/matomo/plugins/Goals/Tracker/GoalsRequestProcessor.php on line 92 and exactly 4 expected 
in /opt/bitnami/matomo/core/Tracker/GoalManager.php:131 
```
Tracking fails.

**Describe the results you expected:**
I expect no errors in the logs and working tracking.

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:53:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     true

```

- Output of `docker info`:

```
Containers: 60
 Running: 16
 Paused: 0
 Stopped: 44
Images: 63
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: ivmrai7yydhi9ocusovuteayo
 Is Manager: true
 ClusterID: f8ciyyn6ji7i7ysz6bpufq8kt
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 88.198.33.38
 Manager Addresses:
  88.198.33.38:2377
Runtimes: nvidia runc
Default Runtime: nvidia
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 12f6a991201fdb8f82579582d5e00e28fba06d0a-dirty
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-45-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.77GiB
Name: cartman
ID: EH6N:2XWI:37YK:BRTU:5VPC:WBBV:FB7I:5CNB:6A5A:LH3K:V5UD:NOZL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Comment by pixlol** [comment]
An manual update as described here https://github.com/matomo-org/matomo/issues/14698 did lead to other PHP errors.

**Comment by carrodher** [comment]
Hi,
From `matomo:3.8.1-ol-7-r20` to `3.11.0-ol-7-r20` there are more changes apart from the application version itself. MariaDB was upgraded from `10.1` to `10.3`, in the same way, PHP version was upgraded from `7.1` to `7.3`.

Can you try following the [steps documented in the README](https://github.com/bitnami/bitnami-docker-matomo#upgrading-matomo)?

**Comment by pixlol** [comment]
Well, I use the images in a stack and run them as services, so the README does not apply in all points, but in general these are steps, that have been done. 

After the update of the compose file the stack with the services has been newly deployed. This leads to a stop of the old container and a start of the new one. 

The env CONFIGURATION has not been changed.

The MariaDB is 'bitnami/mariadb:latest' so this should no be a problem also.

I also was able to update Matomo from the dashboard without problems, but this update will not survive an restart of the service.

Any ideas what is the cause here and how to solve this issue?

**Comment by carrodher** [comment]
Hi, I am trying to reproduce it.

Those are the steps I currently did:
- Clone this repository, go to _ol-7_ directory and checkout to the commit a0e95dd (the one with `matomo:3.8.1-ol-7-r20` files, not only the image tag)
```bash
git clone git@github.com:bitnami/bitnami-docker-matomo.git
cd 3/ol-7
git checkout a0e95dd
```
- Replace the rolling tag in the _docker-compose_:
```diff
     volumes:
       - 'mariadb_data:/bitnami'
   matomo:
-    image: 'bitnami/matomo:3-ol-7'
+    image: 'bitnami/matomo:3.8.1-ol-7-r20'
     environment:
       - MARIADB_HOST=mariadb
       - MARIADB_PORT_NUMBER=3306
```
- With the previous steps, we reached the status when the `3.8.1-ol-7-r20` tag was released, not only in terms of image but also files, env. variables, mariadb version, etc.
- By running `docker-compose up` I deployed a functional Matomo, and as you rightly said, a warning about new version appears in the UI:

![Screen Shot 2019-08-07 at 11 24 10](https://user-images.githubusercontent.com/13216600/62611729-6d86bd80-b906-11e9-9cc6-3a8f09f3edd5.png)

- I updated Matomo following the UI instructions, at this time there are no warnings about the version:

![Screen Shot 2019-08-07 at 11 25 52](https://user-images.githubusercontent.com/13216600/62611728-6cee2700-b906-11e9-834e-f81ca6a006c3.png)

![Screen Shot 2019-08-07 at 11 27 27](https://user-images.githubusercontent.com/13216600/62611727-6cee2700-b906-11e9-9614-4ab6968d3f8d.png)

As you rightly said, the above steps are not persisted between executions because the code itself is not persisted, so the codebase after the restart comes back to the old version while the database was upgraded to the new version.

In this case, replacing the old image by the new one should work if you are also updating the database schema as the upgrade via UI did. But maybe this is not working because of the MariaDB different version, `bitnami/mariadb:latest` is a rolling tag, if you deployed this image some months ago, this tag was pointing to MariaDB 10.1, while now it is pointing to 10.3.

I also did the following test:
- Replace the Matomo image in the current _docker-compose_, so the deploy will use the new components (mariadb, php, etc) but the old image:
```bash
git checkout master
vim docker-compose.yaml
```
```diff
     volumes:
       - 'mariadb_data:/bitnami'
   matomo:
-    image: 'bitnami/matomo:3-ol-7'
+    image: 'bitnami/matomo:3.8.1-ol-7-r20'
     environment:
       - MARIADB_HOST=mariadb
       - MARIADB_PORT_NUMBER=3306
```
- As expected, the warning about the new version available appears in the UI
- Replacing the image by the new one everything works fine without any upgrade process.

With the above tests I was not able to reproduce your issue, please, can you provide specific steps to reproduce it? I mean, something like:
- I have a deploy with matomo X, mariadb Y
- Replace the image
- Exucete `blabla`
- Restart
- The issue appears

**Comment by kenzonarita** [comment]
@pixlol I was having the same issue - check your mounts. If you have mounted a volume for db persistence in the way that is recommended in the README, then your matomo plugins will have been cached, and will be mounted on top of the new version's plugins directory.

I'm guessing this is intentional, so that you don't have to reinstall/extend the image to keep any extra plugins @carrodher ? Not sure what a good solution is if the default plugins change regularly...

**Comment by carrodher** [comment]
To ensure that the useful data that is not stored in the database is persisted between execution,  we are mounting it in a volume. Currently, we are persisting the following directories: `config/config.ini.php` and `plugins`.

It is not a cache or something similar, we are persisting the whole folder where plugins are installed, so plugins are updated as usual. In my opinion, the issue, in this case, appears because of some incompatibilities between the installed plugin version with the new Matomo version or some of the components included in the image, like PHP (moved from `7.1` to `7.3`) or MySQL (client moved from `10.1` to `10.3`)

**Comment by pixlol** [comment]
Thank you all for the quick and helpful answers. I could not do a succesful update as described above:

* Run the update from inside matomo to the new version including a database update if needed
* Stop the service/container running the old version
* Start the service/container running the new version

The startup is now without errors and everything is persisted as it should be. 

@carrodher Maybe you could add this steps to the readme, as it indeed seems to be a problem, that the plugins stay on the old version`s state, when only the image of the container is updated.

**Comment by carrodher** [comment]
We are glad that you were able to fix the issue. If you have any other questions, please do not hesitate to let us know.

I just created an internal task to improve the README. Thanks!

**Comment by bigbrozer** [comment]
Pardon me to reactivate this issue...

Just did the update from 3.10 --> 3.11. I confirm what @kenzonarita is saying, we are persisting `/bitnami` folder in the container to an external volume so the embedded plugins did not get the updates (previous plugins versions are mounted on top of new ones) and I was not able to verify if the image is "copying" new plugins versions... we are using Kubernetes, maybe we should think about an initContainer to copy back new plugins over the persisted one...

Here is what I got just before the 500 error:

```plain
[Thu Sep 19 12:02:14.959048 2019] [php7:error] [pid 123] [client 172.18.9.32:43398] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Piwik\\Tracker\\GoalManager::detectGoalsMatchingUrl(), 2 passed in /bitnami/matomo/plugins/Goals/Tracker/GoalsRequestProcessor.php on line 92 and exactly 4 expected in /opt/bitnami/matomo/core/Tracker/GoalManager.php:131\nStack trace:\n#0 /bitnami/matomo/plugins/Goals/Tracker/GoalsRequestProcessor.php(92): Piwik\\Tracker\\GoalManager->detectGoalsMatchingUrl(11, Object(Piwik\\Tracker\\ActionPageview))\n#1 /opt/bitnami/matomo/core/Tracker/Visit.php(152): Piwik\\Plugins\\Goals\\Tracker\\GoalsRequestProcessor->afterRequestProcessed(Object(Piwik\\Tracker\\Visit\\VisitProperties), Object(Piwik\\Tracker\\Request))\n#2 /opt/bitnami/matomo/core/Tracker.php(138): Piwik\\Tracker\\Visit->handle()\n#3 /opt/bitnami/matomo/core/Tracker/Handler.php(49): Piwik\\Tracker->trackRequest(Object(Piwik\\Tracker\\Request))\n#4 /opt/bitnami/matomo/core/Tracker.php(120): Piwik\\Tracker\\Handler->process(Object(Piwik\\Tracker), Object(Piwik\\Tracker\\RequestSet))\n#5 /opt/bitnami/matomo/core/Tracker.php(97): P in /opt/bitnami/matomo/core/Tracker/GoalManager.php on line 131
```

This is working using the web updater because files are copied over existing ones but when your container restart you may cause some mess...

**Comment by carrodher** [comment]
Plugins maintained by [Matomo (Piwik)](http://plugins.matomo.org/developer/piwik) and plugins by [InnoCraft](http://plugins.matomo.org/developer/innocraft) are compatible for sure with the latest Matomo version. For all other 3rd party plugins the official documentation recommends to go to the [Matomo Marketplace](http://plugins.matomo.org/), click on the Plugin and then check in the bottom part where it says “Requirements” whether this plugin is compatible with the latest Matomo.

- If the plugin is compatible with the latest Matomo, it will be likely updated to the latest compatible version automatically.

- If the plugin is not compatible, it will be deactivated during the process; or if the plugin has not specified its compatibility correctly, the ‘Safe mode’ might be displayed, letting you disable the incompatible plugin to make Matomo work again.

That is the theory, but maybe it is not working in this specific case. Can you try the update disabling the plugins? What plugins are installed?
